### PR TITLE
Use v3 API from burrow 1.0

### PR DESCRIPTION
**Pull request by lalinsky**

### CODE REVIEW

**Comment by cl0udgeek** [comment]
bump bump

**Review by mical85 — APPROVED** [review]

**Comment by cl0udgeek** [comment]
Just did a build off of this PR and got this error when running it against master branch of Burrow...

```2017-12-20 15:21:10,733 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Starting.
Exception in thread "Thread-0" play.api.libs.json.JsResultException: JsResultException(errors:List((/totallag,List(ValidationError(List(error.expected.int),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsDefined.as(JsLookup.scala:132)
	at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:113)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$2.apply(OffsetMonitor.scala:135)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$2.apply(OffsetMonitor.scala:135)
	at scala.collection.immutable.List.map(List.scala:277)
	at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:135)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$6.apply(OffsetMonitor.scala:149)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$6.apply(OffsetMonitor.scala:149)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:149)
	at com.github.splee.burrower.OffsetMonitor.run(OffsetMonitor.scala:69)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by lalinsky** [comment]
Hm, I must have missed one more place where the type changed. Unfortunately, I'm no longer able to fix this.

**Comment by sotosof** [comment]
@k1ng87 Can you please test this PR again?

**Comment by TronPaul** [comment]
Is there a reason to not use `current_lag` over `end.lag`? I've been trying out burrower built with this PR and some other changes and noticed that if a consumer is stopped burrower reports its lag as 0 as burrow only update's `end` on a new offset commit.

**Comment by phas13** [comment]
```
2018-04-06 12:08:04,851 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Creating influxdb writer...
2018-04-06 12:08:04,988 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Creating monitor...
2018-04-06 12:08:04,989 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Starting.
Exception in thread "Thread-1" play.api.libs.json.JsResultException: JsResultException(errors:List((/partitions(16)/start/lag,List(ValidationError(List(error.path.missing),WrappedArray()))), ..., (/partitions(511)/end/lag,List(ValidationError(List(error.path.missing),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
	at play.api.libs.json.JsDefined.as(JsLookup.scala:132)
	at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:113)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$2.apply(OffsetMonitor.scala:135)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$2.apply(OffsetMonitor.scala:135)
	at scala.collection.immutable.List.map(List.scala:277)
	at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:135)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$6.apply(OffsetMonitor.scala:149)
	at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$6.apply(OffsetMonitor.scala:149)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:149)
	at com.github.splee.burrower.OffsetMonitor.run(OffsetMonitor.scala:69)
	at java.lang.Thread.run(Thread.java:748)
2018-04-06 12:08:06,016 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Done.
```

**Comment by pgibert** [comment]
hello same problem for me  with burrow started on ubuntu box :
2018-04-27 08:04:43,237 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Starting.
Exception in thread "Thread-0" play.api.libs.json.JsResultException: JsResultException(errors:List((/complete,List(ValidationError(List(error.expected.jsboolean),WrappedArray())))))
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
        at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
        at play.api.libs.json.JsError.fold(JsResult.scala:13)
        at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
        at play.api.libs.json.JsDefined.as(JsLookup.scala:132)
        at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:113)
        at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$2.apply(OffsetMonitor.scala:135)
        at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$2.apply(OffsetMonitor.scala:135)
        at scala.collection.immutable.List.map(List.scala:273)
        at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:135)
        at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$6.apply(OffsetMonitor.scala:149)
        at com.github.splee.burrower.OffsetMonitor$$anonfun$getLag$6.apply(OffsetMonitor.scala:149)
        at scala.collection.immutable.List.map(List.scala:273)
        at com.github.splee.burrower.OffsetMonitor.getLag(OffsetMonitor.scala:149)
        at com.github.splee.burrower.OffsetMonitor.run(OffsetMonitor.scala:69)
        at java.lang.Thread.run(Thread.java:745)
2018-04-27 08:04:43,752 INFO  [main] com.github.splee.burrower.OffsetMonitor$ - Done.

**Pull request closed without merging**
